Repository Dev-FE-2/toy-project3-team4, pull requests merged in 2025-01, with the labels that each got.

#3 [Settings] 라이브러리 및 템플릿 추가 생성
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: ⚙ Settings

#4 [Settings] issue 템플릿 생성
  .github/ISSUE_TEMPLATE/bugfix.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/settings.yml
Labels: ⚙ Settings

#9 settings: tsconfig에서 프로젝트 절대경로 설정 추가 (#8)
  tsconfig.app.json
Labels: ⚙ Settings

#13 [🔨 Refactor] 라우터 코드 버전 최신화
  src/components/NavBar/NavBar.tsx
  src/constant/navigation.ts
  src/constant/url.ts
  src/pages/FollowListPage/FollowListPage.tsx
  src/pages/FollowListPage/index.ts
  src/pages/FollowPlaylistPage/FollowPlaylistPage.tsx
  src/pages/FollowPlaylistPage/index.ts
  src/pages/InterestPage/InterestPage.tsx
  src/pages/InterestPage/index.ts
  src/pages/PlaylistViewPage/PlaylistViewPage.tsx
  src/pages/PlaylistViewPage/index.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/index.ts
  src/pages/UpsertPlaylistPage/UpsertPlaylistPage.tsx
  src/pages/UpsertPlaylistPage/index.ts
  src/pages/UserInfoPage/UserInfoPage.tsx
  src/pages/UserInfoPage/index.ts
  src/pages/index.ts
  src/routes/AppRoutes.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/routeConfig.tsx
  src/utils/navigate.ts
Labels: 🔨 Refactor, 🔨 Fix

#14 [🔨 Fix] figma의 스타일 가이드로 색상으로 semantic design token 수정
  src/GlobalStyle.ts
  src/styles/token/colors/index.ts
  src/styles/token/colors/rawValue.ts
  src/styles/token/colors/scale.ts
  src/styles/token/colors/semantic.ts
Labels: 🎨 Design, 🔨 Fix

#17 [⚙ Settings] Firebase 연동 설정
  .gitignore
  package-lock.json
  package.json
  src/api/firebase/config.ts
  src/api/firebase/index.ts
Labels: ⚙ Settings

#20 [✨ Feature] 프로젝트 반응형 레이아웃 UI 작업
  index.html
  public/favicon.ico
  public/logo_petmoment.svg
  public/vite.svg
  src/assets/avatar.svg
  src/assets/react.svg
  src/components/NavBar/NavBar.styles.ts
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/index.ts
  src/components/core/ProfileImage/ProfileImage.styles.ts
  src/components/core/ProfileImage/ProfileImage.tsx
  src/components/core/ProfileImage/index.ts
  src/components/core/index.ts
  src/components/index.ts
  src/components/layout/Logo/Logo.styles.ts
  src/components/layout/Logo/Logo.tsx
  src/components/layout/Logo/index.ts
  src/components/layout/MobileHeader/MobileHeader.styles.ts
  src/components/layout/MobileHeader/MobileHeader.tsx
  src/components/layout/MobileHeader/index.ts
  src/components/layout/MobileNavBar/MobileNavBar.styles.ts
  src/components/layout/MobileNavBar/MobileNavBar.tsx
  src/components/layout/MobileNavBar/index.ts
  src/components/layout/SideNavBar/SideNavBar.styles.ts
  src/components/layout/SideNavBar/SideNavBar.tsx
  src/components/layout/SideNavBar/index.ts
  src/components/layout/index.ts
  src/constant/navigation.ts
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/styles/index.ts
  src/styles/token/border.ts
  src/styles/token/colors/semantic.ts
  src/styles/token/font.ts
  src/styles/token/height.ts
  src/styles/token/index.ts
Labels: ✨ Feature, 🎨 Design, 🔨 Fix

#16 [Feat] 공용으로 사용될 버튼 컴포넌트 개발
  src/components/core/Button.tsx
  src/components/core/index.ts
Labels: ✨ Feature, 🎨 Design

#23 [Fix] globalStyle과 디자인 토큰 값을 rem 단위로 변경
  src/GlobalStyle.ts
  src/styles/token/font.ts
  src/styles/token/height.ts
  src/styles/token/padding.ts
Labels: 🎨 Design, 🔨 Fix

#25 [✨ Feature] 로그인 페이지 마크업
  src/assets/google.svg
  src/components/GoogleLoginButton/GoogleLoginButton.styles.tsx
  src/components/GoogleLoginButton/GoogleLoginButton.tsx
  src/components/GoogleLoginButton/index.ts
  src/components/index.ts
  src/pages/SignInPage/SignInPage.styles.ts
  src/pages/SignInPage/SignInPage.tsx
Labels: 🎨 Design

#26 [🔨 Fix] 반응형 레이아웃 UI 피드백 반영
  src/components/core/ProfileImage/ProfileImage.styles.ts
  src/components/core/ProfileImage/ProfileImage.tsx
  src/components/layout/Logo/Logo.styles.ts
  src/components/layout/Logo/Logo.tsx
  src/components/layout/MobileHeader/MobileHeader.styles.ts
  src/components/layout/MobileHeader/MobileHeader.tsx
  src/components/layout/MobileNavBar/MobileNavBar.styles.ts
  src/components/layout/MobileNavBar/MobileNavBar.tsx
  src/components/layout/SideNavBar/SideNavBar.styles.ts
  src/components/layout/SideNavBar/SideNavBar.tsx
  src/constant/navigation.ts
  src/layout/Layout.styles.ts
  src/layout/Layout.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🔨 Fix

#28 [⚙ Settings] react-icons 라이브러리 설치
  package-lock.json
  package.json
Labels: ⚙ Settings

#31 [Style] globalStyle의 폰트 사이즈 기준 변경
  src/GlobalStyle.ts
Labels: 🎨 Design, 🔨 Fix

#33 [🔨 Fix] font 디자인 토큰 업데이트
  src/styles/token/font.ts
Labels: 🔨 Fix

#34 [⚙ Settings] Stylelint 설치와 styled-components 관련 린트 설정
  .stylelintrc.json
  package-lock.json
  package.json
  vite.config.ts
Labels: ⚙ Settings

#37 [🔨 Fix] padding 디자인 토큰 값 2.4 rem (24px) 값 추가
  src/styles/token/padding.ts
Labels: 🎨 Design, 🔨 Fix

#39 [🐞 BugFix] 더 이상 지원하지 않는 stylelint-config-styled-components 라이브러리 제거
  .stylelintrc.json
  package-lock.json
  package.json
Labels: 🐞 BugFix, ⚙ Settings, 🔨 Fix

#42 [FEAT] 프로필 페이지에 사용자 정보 렌더링을 위한 컴포넌트 구현
  src/components/card/ProfileCard/ProfileCard.styles.ts
  src/components/card/ProfileCard/ProfileCard.tsx
  src/components/card/ProfileCard/index.ts
Labels: 🎨 Design

#44 [FEAT] 검색, 프로필 페이지에서 무한 로딩에 사용 될 플레이 리스트 카드 컴포넌트 구현
  src/assets/testThumbnail.png
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.styles.ts
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.tsx
  src/components/card/ExplorePlayListCard/index.ts
Labels: 🎨 Design

#47 [FEAT] 검색 페이지에서 무한 로딩에 사용될 사용자 카드 컴포넌트 마크업
  src/components/card/UserCard/UserCard.styles.ts
  src/components/card/UserCard/UserCard.tsx
  src/components/card/UserCard/index.ts
  src/components/card/index.ts
  src/components/index.ts
Labels: ✨ Feature, 🎨 Design

#46 [✨ Feature] 로딩 컴포넌트(스피너) 추가
  package-lock.json
  package.json
  src/components/core/Loader/LoaderWrapper.styles.ts
  src/components/core/Loader/LoaderWrapper.tsx
  src/components/core/Loader/index.ts
  src/components/core/index.ts
  src/layout/Layout.styles.ts
Labels: ⚙ Settings, ✨ Feature

#57 [🔨 Fix] 로그인 상태에 따른 route 오류 및 userStore 액션 이름 설정
  src/hooks/useAuth.ts
  src/routes/routeConfig.tsx
  src/store/index.ts
  src/store/userStore.ts
Labels: 🐞 BugFix, 🔨 Fix

#55 [FIX] 디자인 시스템 변경에 의한 컬러 토큰값 변경
  src/components/button/Button.tsx
  src/components/button/GoogleLoginButton/GoogleLoginButton.styles.tsx
  src/components/button/GoogleLoginButton/GoogleLoginButton.tsx
  src/components/button/GoogleLoginButton/index.ts
  src/components/button/index.ts
  src/components/core/index.ts
  src/components/index.ts
  src/components/signin/index.ts
  src/styles/token/colors/semantic.ts
Labels: 🔨 Fix

#53 [✨ Feature] 사이드바 네비게이션의 더보기 dropdown UI 와 활성화 UI 작업
  src/components/core/ProfileImage/ProfileImage.styles.ts
  src/components/core/ProfileImage/ProfileImage.tsx
  src/components/layout/MobileNavBar/MobileNavBar.tsx
  src/components/layout/SideNavBar/SideNavBar.tsx
  src/components/layout/common/Logo/Logo.styles.ts
  src/components/layout/common/Logo/Logo.tsx
  src/components/layout/common/Logo/index.ts
  src/components/layout/common/NavMenu/NavMenu.styles.ts
  src/components/layout/common/NavMenu/NavMenu.tsx
  src/components/layout/common/NavMenu/index.ts
  src/components/layout/common/index.ts
  src/components/layout/desktop/index.ts
  src/components/layout/desktop/sidebar/MoreMenu/MoreMenu.styles.ts
  src/components/layout/desktop/sidebar/MoreMenu/MoreMenu.tsx
  src/components/layout/desktop/sidebar/MoreMenu/index.ts
  src/components/layout/desktop/sidebar/SideNavBar/SideNavBar.styles.ts
  src/components/layout/desktop/sidebar/SideNavBar/SideNavBar.tsx
  src/components/layout/desktop/sidebar/SideNavBar/index.ts
  src/components/layout/desktop/sidebar/SideNavItem/SideNavItem.styles.ts
  src/components/layout/desktop/sidebar/SideNavItem/SideNavItem.tsx
  src/components/layout/desktop/sidebar/SideNavItem/index.ts
  src/components/layout/desktop/sidebar/index.ts
  src/components/layout/index.ts
  src/components/layout/mobile/MobileHeader/MobileHeader.styles.ts
  src/components/layout/mobile/MobileHeader/MobileHeader.tsx
  src/components/layout/mobile/MobileHeader/index.ts
  src/components/layout/mobile/MobileNavBar/MobileNavBar.styles.ts
  src/components/layout/mobile/MobileNavBar/MobileNavBar.tsx
  src/components/layout/mobile/MobileNavBar/index.ts
  src/components/layout/mobile/index.ts
  src/constant/index.ts
  src/constant/navItems.ts
  src/hooks/index.ts
  src/hooks/useVisibilityToggle.ts
  src/navigation/index.ts
  src/navigation/navItems.tsx
  src/styles/token/height.ts
Labels: ✨ Feature, 🎨 Design

#60 [✨ Feature] 관심사 선택 페이지 마크업
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.tsx
  src/components/core/PageTitle/PageTitle.styles.ts
  src/components/core/PageTitle/PageTitle.tsx
  src/components/core/PageTitle/index.ts
  src/components/core/index.ts
  src/constant/index.ts
  src/constant/interests.ts
  src/pages/InterestPage/InterestPage.styles.ts
  src/pages/InterestPage/InterestPage.tsx
Labels: 🎨 Design

#62 [✨ Feature] firestore 관련 공통 유틸함수 개발
  src/api/service/user/userService.ts
  src/utils/dbUtil.ts
  src/utils/index.ts
Labels: ✨ Feature, 🔨 Refactor

#67 [🔨 Fix] 로그인 후 유저정보 persist 설정
  src/App.tsx
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useAuthObserver.ts
  src/routes/AuthRoute.tsx
  src/store/userStore.ts
  src/utils/format.ts
Labels: 🔨 Fix

#69 [✨ Feature] 관심사 선택 기능 개발
  src/constant/interests.ts
  src/hooks/index.ts
  src/hooks/useInterestSelection.ts
  src/pages/InterestPage/InterestPage.styles.ts
  src/pages/InterestPage/InterestPage.tsx
  src/types/userTypes.ts
Labels: ✨ Feature

#70 [FEAT] 사용자 정보 수정 페이지 개발 및 추가 요청 사항 구현
  src/App.tsx
  src/api/service/user/index.ts
  src/api/service/user/updateUserInfo.ts
  src/components/core/RoundImage/RoundImage.styles.ts
  src/components/core/RoundImage/RoundImage.tsx
  src/components/core/RoundImage/index.ts
  src/components/core/index.ts
  src/hooks/index.ts
  src/hooks/useFetchUserInfo.ts
  src/pages/UserInfoPage/UserInfoPage.styles.ts
  src/pages/UserInfoPage/UserInfoPage.tsx
  src/provider/index.ts
  src/provider/queryClient.ts
Labels: ✨ Feature, 🎨 Design, ☕️ Chore

#72 [✨ Feature] Input, Textarea 컴포넌트 생성
  src/components/core/Input/Input.styles.ts
  src/components/core/Input/Input.tsx
  src/components/core/Input/index.ts
  src/components/core/Textarea/Textarea.styles.ts
  src/components/core/Textarea/Textarea.tsx
  src/components/core/Textarea/index.ts
  src/components/core/index.ts
Labels: ✨ Feature, 🎨 Design

#74 [✨ Feature] 플레이리스트 생성/수정 페이지 마크업
  package-lock.json
  package.json
  src/components/core/Switch/Switch.styles.ts
  src/components/core/Switch/Switch.tsx
  src/components/core/Switch/index.ts
  src/components/core/index.ts
  src/pages/UpsertPlaylistPage/UpsertPlaylistPage.styles.ts
  src/pages/UpsertPlaylistPage/UpsertPlaylistPage.tsx
Labels: ✨ Feature, 🎨 Design

#73 [✨ Feature] 데스크탑 사이드바와 모바일 헤더의 검색 · 설정의 확장 UI와 팔로우 리스트 nav UI
  src/components/core/Input/Input.tsx
  src/components/core/ProfileImage/ProfileImage.tsx
  src/components/layout/common/FollowNavMenu/FollowNavMenu.styles.ts
  src/components/layout/common/FollowNavMenu/FollowNavMenu.tsx
  src/components/layout/common/FollowNavMenu/index.ts
  src/components/layout/common/MyProfileImage.tsx
  src/components/layout/common/NavMenu/NavMenu.tsx
  src/components/layout/common/SearchHistoryList/SearchHistoryList.styles.ts
  src/components/layout/common/SearchHistoryList/SearchHistoryList.tsx
  src/components/layout/common/SearchHistoryList/index.ts
  src/components/layout/common/SearchInput.tsx
  src/components/layout/common/index.ts
  src/components/layout/desktop/sidebar/ConfigMenuDropdown/ConfigMenuDropdown.styles.ts
  src/components/layout/desktop/sidebar/ConfigMenuDropdown/ConfigMenuDropdown.tsx
  src/components/layout/desktop/sidebar/ConfigMenuDropdown/index.ts
  src/components/layout/desktop/sidebar/FollowNavItems/FollowNavItems.styles.ts
  src/components/layout/desktop/sidebar/FollowNavItems/FollowNavItems.tsx
  src/components/layout/desktop/sidebar/FollowNavItems/index.ts
  src/components/layout/desktop/sidebar/MainNavItems/MainNavItems.tsx
  src/components/layout/desktop/sidebar/MainNavItems/index.ts
  src/components/layout/desktop/sidebar/MoreMenu/MoreMenu.tsx
  src/components/layout/desktop/sidebar/MoreMenu/index.ts
  src/components/layout/desktop/sidebar/MoreNavItems/MoreNavItems.styles.ts
  src/components/layout/desktop/sidebar/MoreNavItems/MoreNavItems.tsx
  src/components/layout/desktop/sidebar/MoreNavItems/index.ts
  src/components/layout/desktop/sidebar/SearchFormSideDropdown/SearchFormSideDropdown.styles.ts
  src/components/layout/desktop/sidebar/SearchFormSideDropdown/SearchFormSideDropdown.tsx
  src/components/layout/desktop/sidebar/SearchFormSideDropdown/index.ts
  src/components/layout/desktop/sidebar/SideNavBar/SideNavBar.styles.ts
  src/components/layout/desktop/sidebar/SideNavBar/SideNavBar.tsx
  src/components/layout/desktop/sidebar/SideNavItem/SideNavItem.styles.ts
  src/components/layout/desktop/sidebar/SideNavItem/SideNavItem.tsx
  src/components/layout/desktop/sidebar/index.ts
  src/components/layout/mobile/MobileHeader/MobileHeader.styles.ts
  src/components/layout/mobile/MobileHeader/MobileHeader.tsx
  src/components/layout/mobile/MobileMoreWrap.tsx
  src/components/layout/mobile/MobileSearchWrap.tsx
  src/components/layout/mobile/SearchHistoryDropdown/SearchHistoryDropdown.styles.ts
  src/components/layout/mobile/SearchHistoryDropdown/SearchHistoryDropdown.tsx
  src/components/layout/mobile/SearchHistoryDropdown/index.ts
  src/components/layout/mobile/index.ts
  src/hooks/useVisibilityToggle.ts
  src/styles/token/colors/semantic.ts
Labels: ✨ Feature, 🎨 Design

#78 [✨ Feature] 공통 태그 컴포넌트 구현
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.styles.ts
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.tsx
  src/components/core/RoundTag/RoundTag.styles.ts
  src/components/core/RoundTag/RoundTag.tsx
  src/components/core/RoundTag/index.ts
  src/components/core/TagList/index.ts
  src/components/core/TextTag/TextTag.styles.ts
  src/components/core/TextTag/TextTag.tsx
  src/components/core/TextTag/index.ts
  src/components/core/index.ts
Labels: ✨ Feature

#79 fix: input, textarea 공용 컴포넌트 수정 (#77)
  src/components/core/Input/Input.styles.ts
  src/components/core/Input/Input.tsx
  src/components/core/Textarea/Textarea.styles.ts
  src/components/core/Textarea/Textarea.tsx
  src/components/layout/common/SearchInput.tsx
Labels: 🎨 Design, 🔨 Fix

#81 [Fix] 누락된 taglist 파일 추가
  src/components/core/RoundTag/RoundTag.tsx
  src/components/core/TagList/TagList.styles.ts
  src/components/core/TagList/TagList.tsx
Labels: 🐞 BugFix

#84 [🐞 BugFix] 사이드바 더보기 드롭다운 메뉴 에러 수정
  src/components/layout/desktop/sidebar/MoreNavItems/MoreNavItems.tsx
Labels: 🐞 BugFix

#86 [✨ Feature] 파이어스토어 DB의 playlist API 함수와 tanstack-query를 적용한 커스텀 훅 생성
  src/api/service/index.ts
  src/api/service/playlist/index.ts
  src/api/service/playlist/playlistService.ts
  src/hooks/index.ts
  src/hooks/playlist/index.ts
  src/hooks/playlist/useDeletePlaylist.ts
  src/hooks/playlist/useFetchPlaylist.ts
  src/hooks/playlist/usePostPlaylist.ts
  src/hooks/playlist/useUpdatePlaylist.ts
  src/types/index.ts
  src/types/playlistTypes.ts
Labels: ✨ Feature

#87 [FIX] 검색폼 재사용성을 위해 폴더 구조와 코드 수정
  src/components/layout/common/SearchHistoryList/SearchHistoryList.styles.ts
  src/components/layout/common/SearchHistoryList/SearchHistoryList.tsx
  src/components/layout/common/SearchHistoryList/index.ts
  src/components/layout/common/SearchInput.tsx
  src/components/layout/common/index.ts
  src/components/layout/desktop/sidebar/DesktopSearch/DesktopSearch.styles.ts
  src/components/layout/desktop/sidebar/DesktopSearch/DesktopSearch.tsx
  src/components/layout/desktop/sidebar/DesktopSearch/index.ts
  src/components/layout/desktop/sidebar/MainNavItems/MainNavItems.tsx
  src/components/layout/desktop/sidebar/SearchFormSideDropdown/index.ts
  src/components/layout/desktop/sidebar/index.ts
  src/components/layout/mobile/MobileHeader/MobileHeader.tsx
  src/components/layout/mobile/MobileSearch/MobileSearch.styles.ts
  src/components/layout/mobile/MobileSearch/MobileSearch.tsx
  src/components/layout/mobile/MobileSearch/index.ts
  src/components/layout/mobile/MobileSearchWrap.tsx
  src/components/layout/mobile/SearchHistoryDropdown/SearchHistoryDropdown.tsx
  src/components/layout/mobile/SearchHistoryDropdown/index.ts
  src/components/layout/mobile/index.ts
  src/components/search/SearchForm/SearchForm.styles.ts
  src/components/search/SearchForm/SearchForm.tsx
  src/components/search/SearchForm/index.ts
  src/components/search/SearchHistory/SearchHistory.styles.ts
  src/components/search/SearchHistory/SearchHistory.tsx
  src/components/search/SearchHistory/index.ts
  src/components/search/index.ts
Labels: 🎨 Design, 🔨 Fix

#90 [FIX] 사용자 인터렉션에 대한 UI 변화를 위한 검색폼 수정
  src/components/layout/desktop/sidebar/DesktopSearch/DesktopSearch.tsx
  src/components/layout/desktop/sidebar/MainNavItems/MainNavItems.tsx
  src/components/layout/mobile/MobileSearch/MobileSearch.tsx
  src/components/search/SearchForm/SearchForm.tsx
  src/components/search/SearchHistory/SearchHistory.tsx
  src/store/index.ts
  src/store/searchHistoryStore.ts
Labels: ✨ Feature, 🔨 Fix

#89 [✨ Feature] 파이어스토어 콜랙션 DB의 전체 Document 호출하는 유틸함수와 useFetchAllPlaylist 커스텀 훅 추가
  src/api/service/playlist/playlistService.ts
  src/hooks/playlist/index.ts
  src/hooks/playlist/useFetchAllPlaylist.ts
  src/utils/dbUtil.ts
Labels: ✨ Feature

#91 [✨ Feature] 플레이리스트 생성/수정 기능 구현
  src/api/service/index.ts
  src/api/service/video/index.ts
  src/api/service/video/videoService.ts
  src/components/card/PlayListVideoCard/PlayListVideoCard.styles.ts
  src/components/card/PlayListVideoCard/PlayListVideoCard.tsx
  src/components/card/PlayListVideoCard/index.ts
  src/components/card/index.ts
  src/components/core/RoundTag/RoundTag.tsx
  src/components/core/TagList/TagList.styles.ts
  src/components/core/TagList/TagList.tsx
  src/components/form/EditTagSection/EditTagSection.tsx
  src/components/form/EditTagSection/index.ts
  src/components/form/EditVideoSection/EditVideoSection.styles.ts
  src/components/form/EditVideoSection/EditVideoSection.tsx
  src/components/form/EditVideoSection/index.ts
  src/components/form/FormItem/FormItem.styles.ts
  src/components/form/FormItem/FormItem.tsx
  src/components/form/FormItem/index.ts
  src/components/form/PlayListForm/PlayListForm.styles.ts
  src/components/form/PlayListForm/PlayListForm.tsx
  src/components/form/PlayListForm/index.ts
  src/components/form/index.ts
  src/components/index.ts
  src/constant/index.ts
  src/constant/playlistLimits.ts
  src/constant/url.ts
  src/context/PlaylistContext.ts
  src/context/index.ts
  src/hooks/index.ts
  src/hooks/useTagEdit.ts
  src/hooks/useVideoEdit.ts
  src/pages/UpsertPlaylistPage/UpsertPlaylistPage.styles.ts
  src/pages/UpsertPlaylistPage/UpsertPlaylistPage.tsx
  src/provider/index.ts
  src/provider/playlistProvider.tsx
  src/types/index.ts
  src/types/playlistTypes.ts
  src/types/videoTypes.ts
  src/utils/format.ts
Labels: ✨ Feature

#93 [🔨 Fix] 디자인 토큰 업데이트
  src/styles/index.ts
  src/styles/token/colors/semantic.ts
  src/styles/token/font.ts
  src/styles/token/index.ts
  src/styles/token/padding.ts
Labels: 🎨 Design, 🔨 Fix

#94 [✨ Feature] Feed component와 메인 Feed 개발
  src/components/core/ProfileImage/ProfileImage.tsx
  src/components/feeds/Feed/Feed.styles.ts
  src/components/feeds/Feed/Feed.tsx
  src/components/feeds/Feed/index.ts
  src/components/feeds/FeedList/FeedList.tsx
  src/components/feeds/FeedList/index.ts
  src/components/feeds/Thumbnails/Thumbnails.styles.ts
  src/components/feeds/Thumbnails/Thumbnails.tsx
  src/components/feeds/Thumbnails/index.ts
  src/components/feeds/index.ts
  src/components/index.ts
  src/constant/index.ts
  src/constant/query.ts
  src/hooks/index.ts
  src/hooks/playlist/index.ts
  src/hooks/playlist/useFetchAllPlaylist.ts
  src/hooks/playlist/useFetchAuthor.ts
  src/hooks/playlist/useFetchPlaylist.ts
  src/hooks/useCopyToClipboard.ts
  src/hooks/user/index.ts
  src/hooks/user/useFetchMyInfo.ts
  src/layout/Layout.styles.ts
  src/pages/HomePage/HomePage.styles.ts
  src/pages/HomePage/HomePage.tsx
Labels: ✨ Feature, 🎨 Design

#96 [✨ Feature] Feed Interaction bar 컴포넌트와 기능 구현
  src/components/button/LikeButton.tsx
  src/components/button/index.ts
  src/components/feeds/Feed/Feed.tsx
  src/components/feeds/InteractionBar/InteractionBar.styles.ts
  src/components/feeds/InteractionBar/InteractionBar.tsx
  src/components/feeds/InteractionBar/index.ts
  src/components/feeds/index.ts
  src/hooks/user/index.ts
  src/hooks/user/useFetchMyUserInfo.ts
Labels: ✨ Feature, 🎨 Design

#99 [FEAT] 검색, 프로필 페이지 개발
  src/api/service/playlist/playlistService.ts
  src/api/service/user/userService.ts
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.tsx
  src/components/card/ProfileCard/ProfileCard.styles.ts
  src/components/card/ProfileCard/ProfileCard.tsx
  src/components/core/Tab/Tab.styles.ts
  src/components/core/Tab/Tab.tsx
  src/components/core/Tab/index.ts
  src/components/search/SearchHistory/SearchHistory.tsx
  src/pages/ProfilePage/ProfilePage.styles.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SearchPage/SearchPage.styles.ts
  src/pages/SearchPage/SearchPage.tsx
Labels: ✨ Feature

#100 [FIX] 누락되었던 데이터 전달을 위해 data.name 추가
  src/components/card/ProfileCard/ProfileCard.tsx
Labels: 🔨 Fix

#102 [📃 Docs] 프로젝트 정리한 README 파일 업데이트
  README.md
Labels: 📃 Docs

#104 [🎨 Design] 각 페이지별 기능 구현 후 UI 틀어지는 부분 수정
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.styles.ts
  src/components/layout/mobile/MobileSearch/MobileSearch.styles.ts
Labels: 🎨 Design

#107 [🔨 Fix] 플레이리스트 및 프로필 동적 라우팅 수정
  src/constant/url.ts
  src/routes/routeConfig.tsx
Labels: 🔨 Fix

#108 [✨ Feature] Feed Interaction bar 아이콘 별 기능 구현 (좋아요, 북마크, 쿼리 파라미터로 상세페이지 이동)
  src/components/button/BookmarkButton.tsx
  src/components/button/CommentViewButton.tsx
  src/components/button/IconButton.tsx
  src/components/button/IconLink.tsx
  src/components/button/IndexViewButton.tsx
  src/components/button/LikeButton.tsx
  src/components/button/ShareButton.tsx
  src/components/button/index.ts
  src/components/feeds/Feed/Feed.tsx
  src/components/feeds/FeedList/FeedList.tsx
  src/components/feeds/InteractionBar/InteractionBar.tsx
  src/components/feeds/Thumbnails/Thumbnails.styles.ts
  src/components/feeds/Thumbnails/Thumbnails.tsx
  src/constant/endPoint.ts
  src/constant/iconSize.ts
  src/constant/index.ts
  src/constant/navItems.ts
  src/constant/queryParams.ts
  src/constant/reactQuery.ts
  src/constant/url.ts
  src/context/FeedListContext.ts
  src/context/index.ts
  src/hooks/playlist/index.ts
  src/hooks/playlist/useContextFeed.ts
  src/hooks/playlist/useFetchAuthor.ts
  src/hooks/playlist/useUpdateLikes.ts
  src/hooks/playlist/useUpdateMyBookmarks.ts
  src/hooks/user/useFetchMyUserInfo.ts
  src/provider/FeedListProvider.tsx
  src/provider/index.ts
  src/types/userTypes.ts
  src/utils/dbUtil.ts
Labels: ✨ Feature, 🎨 Design

#111 [FEAT] intersection observer api를 사용하여 무한 스크롤을 위한 기능 컴포넌트를 구현합니다.
  src/api/service/playlist/playlistService.ts
  src/api/service/user/userService.ts
  src/components/InfiniteScroll/InfiniteScroll.tsx
  src/components/InfiniteScroll/index.ts
  src/components/card/ExplorePlayListCard/ExplorePlayListCard.tsx
  src/components/card/UserCard/UserCard.tsx
  src/components/index.ts
  src/hooks/playlist/index.ts
  src/hooks/playlist/useSearchPlaylist.ts
  src/hooks/user/index.ts
  src/hooks/user/useSearchUser.ts
  src/pages/SearchPage/SearchPage.tsx
Labels: ✨ Feature, 🔨 Fix

#113 [📃 Docs] README 업데이트
  README.md
Labels: 📃 Docs

#117 [🔨 Refactor] 공통 css를 사용하는 IconButton, IconLink 컴포넌트 리팩토링 및 css 수정
  src/components/button/IconButton.tsx
  src/components/button/IconLink.tsx
  src/styles/iconStyle.ts
  src/styles/index.ts
Labels: 🎨 Design, 🔨 Refactor

#120 [☕️ Chore] 팔로잉 플레이리스트 네비게이션 임시 제거
  src/components/layout/desktop/sidebar/SideNavBar/SideNavBar.tsx
  src/constant/navItems.ts
Labels: ☕️ Chore

#121 [📃 Docs] README 기능 구현 업데이트
  README.md
Labels: 📃 Docs

#123 [FIX] 프로필 페이지 라우팅과 link 정보를 사용자 시리얼 번호로 입력받도록 수정합니다.
  src/components/InfiniteScroll/InfiniteScroll.tsx
  src/components/card/ProfileCard/ProfileCard.tsx
  src/components/card/UserCard/UserCard.styles.ts
  src/components/card/UserCard/UserCard.tsx
  src/components/layout/desktop/sidebar/MainNavItems/MainNavItems.tsx
  src/components/layout/mobile/MobileNavBar/MobileNavBar.tsx
  src/components/layout/mobile/MobileSearch/MobileSearch.styles.ts
  src/components/layout/mobile/MobileSearch/MobileSearch.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SearchPage/SearchPage.tsx
Labels: ✨ Feature, 🔨 Fix

#126 [🔨 Fix] 자동생성되는 재생목록 썸네일 이미지에 맞춰서 보이도록 css 수정
  src/components/feeds/InteractionBar/InteractionBar.styles.ts
  src/components/feeds/Thumbnails/Thumbnails.styles.ts
Labels: 🎨 Design, 🔨 Fix

#127 [🔨 Fix] 로그인 전 프로필 메뉴 라우팅 제어 및 프로필 페이지 라우트 관련 이슈 해결
  src/components/feeds/Feed/Feed.tsx
  src/components/layout/common/NavMenu/NavMenu.tsx
  src/components/layout/desktop/sidebar/MainNavItems/MainNavItems.tsx
  src/components/layout/mobile/MobileHeader/MobileHeader.tsx
  src/components/layout/mobile/MobileNavBar/MobileNavBar.tsx
  src/constant/index.ts
  src/constant/queryParams.ts
  src/constant/url.ts
  src/utils/navigate.ts
Labels: 🔨 Refactor, 🔨 Fix

#129 ⚙ Settings] tanstack/react-query-devtools 설치 및 설정
  package-lock.json
  package.json
  src/App.tsx
Labels: ⚙ Settings

#132 [✨ Feature] 플레이리스트 자동재생 기능 구현
  package-lock.json
  package.json
  src/components/video/VideoPlayer/VideoPlayer.styles.ts
  src/components/video/VideoPlayer/VideoPlayer.tsx
  src/pages/PlaylistViewPage/PlaylistViewPage.tsx
Labels: ✨ Feature

#135 [🔨 Fix] 북마크와 좋아요가 반영되지 않는 캐시 문제 해결과 FeedContext 제거하여 서버상태로만 관리
  src/GlobalStyle.ts
  src/components/button/BookmarkButton.tsx
  src/components/button/LikeButton.tsx
  src/components/feeds/Feed/Feed.styles.ts
  src/components/feeds/Feed/Feed.tsx
  src/components/feeds/FeedList/FeedList.tsx
  src/components/feeds/InteractionBar/InteractionBar.tsx
  src/constant/reactQuery.ts
  src/context/FeedListContext.ts
  src/context/index.ts
  src/hooks/comment/useFetchComments.ts
  src/hooks/playlist/index.ts
  src/hooks/playlist/useContextFeed.ts
  src/hooks/playlist/useFetchAllPlaylist.ts
  src/hooks/playlist/useFetchAuthor.ts
  src/hooks/playlist/useFetchPlaylist.ts
  src/hooks/playlist/useFetchVideos.ts
  src/hooks/playlist/useUpdateLikes.ts
  src/hooks/playlist/useUpdateMyBookmarks.ts
  src/hooks/playlist/useUpdatePlaylist.ts
  src/hooks/user/useFetchMyUserInfo.ts
  src/pages/HomePage/HomePage.styles.ts
  src/provider/FeedListProvider.tsx
  src/provider/index.ts
  src/provider/queryClient.ts
Labels: 🐞 BugFix, 🔨 Fix
